<?php

/**
 * @file
 * Contains epub.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function epub_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the epub module.
    case 'help.page.epub':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a epub generator') . '</p>';
      return $output;

    default:
  }
}
