<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\Entity\Node;
use Drupal\clr\Helper\CLRRecommenderLog;

/**
 * Implements hook_ENTITY_TYPE_presave()
 * 
 * @param EntityInterface $entity
 */
function clr_user_presave(EntityInterface $entity) {
 if($entity->isNew()) {
     $entity->addRole('student');
 }
}

/**
* Implements hook_ENTITY_TYPE_insert().
*/

function clr_node_insert(Node $node) {
    if($node->getType() == 'phase_vorgehensmodell') {
        // Get values from phase_vorgehensmodell node
        $nid = $node->id();
        $phase_id = $node->field_phase_number->value;

        // Get dozent lecturer tools with phase_id
        switch ($phase_id) {
            case 0:
                $tid = 10;
                break;
            case 1:
                $tid = 1;
                break;
            case 2:
                $tid = 2;
                break;
            case 3:
                $tid = 3;
                break;
            case 4:
                $tid = 4;
                break;
            case 5:
                $tid = 5;
                break;
            case 6:
                $tid = 6;
                break;
            case 7:
                $tid = 11;
                break;
        }
        $nodes =  \Drupal::entityTypeManager()->getStorage('node')->loadByProperties(['field_phase_term' => $tid]);
        foreach($nodes as $node) {
            if ($node->getType() == 'lecturertools') {
                // create tool
                $tool = \Drupal\node\Entity\Node::create(['type' => 'tools']);
                $tool->title = $node->title->value;
                $tool->field_benutzt = ['value' => '0'];
                $tool->field_phasenid = $nid;
                $tool->save();
            }
            if ($node->getType() == 'lecturerfiles') {
                // get file id 
                $file = $node->field_documentid->entity;
                $file_id = $file->id();
                // create files
                $tool = \Drupal\node\Entity\Node::create(['type' => 'inputdateien']);
                $tool->title = $node->title->value;
                $tool->field_documentid = $file_id;
                $tool->field_phasenid = $nid;
                $tool->save();
            }
            
        }
        
    }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function clr_node_update(Node $node) {
   
}

/**
* Implements hook_cron().
*/

function clr_cron() {

    // Just get the data from recommender log
    $clrRecommenderLog = new CLRRecommenderLog();
    $data = $clrRecommenderLog->get();

    // Now we want to send it to an endpoint
    $model_id = 1; // We have to ask what this id is and where it will come from! 
    $client =  \Drupal::httpClient();
    $request = $client->post("http://147.172.178.30:5000/concept_recommender/training/" . $model_id, ['json' => $data]);
    $response = json_decode($request->getBody());
    \Drupal::logger('clr_module')->notice($response);
}

